import { precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

self.skipWaiting();
clientsClaim();

// precacheAndRoute will inject the manifest generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST);
