import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

self.skipWaiting();
clientsClaim();

cleanupOutdatedCaches();

// precacheAndRoute will inject the manifest generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST);

// SPA routing fallback
try {
  const handler = createHandlerBoundToURL('index.html');
  const navigationRoute = new NavigationRoute(handler, {
    denylist: [
      new RegExp('^/api/'),
      new RegExp('/[^/]+\\.[^/]+$'),
    ],
  });
  registerRoute(navigationRoute);
} catch (error) {
  console.warn('Navigation fallback setup failed:', error);
}

registerRoute(
  ({ request }) => request.destination === 'image',
  new NetworkFirst({
    cacheName: 'images'
  })
);
